### PR TITLE
Added Canon RF 50mm f1.2 and updated Nikkor Z 35mm f1.8

### PR DESCRIPTION
**Pull request by dibyendumajumdar**

### CODE REVIEW

**Comment by jordens** [comment]
@dibyendumajumdar I'm really sorry for completely missing this PR!
I'm happy to merge these and any others that you have been playing with (I've seen your [58 mm f/0.95 Z noct](https://nbviewer.jupyter.org/github/cameragossip/cameragossip.github.io/blob/master/lensdesigns/Nikkor-Z-Noct-58mm-f0.95.ipynb))

One thing to note though: IME lenses from patent designs tend to be really good on paper (i.e. some lambda/8 of PTP OPD for a typical high-end modern photographic lens). I suspect that the Nikkor is correct but that there is some error in the Canon data. Usual suspects are different interpretations of nd/vd material data, aspheric coefficient notations, conic sign and plus/minus ones, air-vs-vacuum especially in lithography lenses.
Admittedly there are likely similar errors in the other lenses that I've uploaded here.
I played a bit with the f/0.95 nikkor but didn't find the issue yet.

**Comment by dibyendumajumdar** [comment]
@jordens Thank you. I thought you weren't happy with the pull request...
I am not an optician - but a long time enthusiast who is interested in lenses. I wish I had the qualifications to understand how rayopt works. If you would suggest any books I should read I am very keen to learn the maths and the physics.

**Comment by jordens** [comment]
I'll see whether I can add a literature list.

**Comment by jordens** [comment]
https://github.com/quartiq/rayopt#literature

**Comment by dibyendumajumdar** [comment]
@jordens Thank you I noticed. So if I had to get one of them then is it the first one the best? I already have his Modern Lens Design but that seems more geared towards the commercial software use.

**Comment by jordens** [comment]
Smith is a decent balance. You'll find most of them online.

**Pull request merged**
