### PR TITLE
Adding Z Noct Nikkor f0.95

### PR DESCRIPTION
**Pull request by dibyendumajumdar**
Hi @jordens 
Really appreciate rayopt. Here is the Noct Nikkor. 
One issue is that I struggled to get the FNo to match the design spec - I had to reduce the aperture size to get it close to 0.98.
Thanks and Regards
Dibyendu

### CODE REVIEW

**Comment by jordens** [comment]
Given the patent the typical workflow would be to specify the f number and then resize the system to meet that aperture. `rayopt` can do this. I'll see whether I can show how to do it in this example.

But also here, there is likely an error somewhere in the lens data. A lens with 3.4 lambda peak-peak OPD at half field wouldn't be convincing.

**Comment by dibyendumajumdar** [comment]
> Given the patent the typical workflow would be to specify the f number and then resize the system to meet that aperture. `rayopt` can do this. I'll see whether I can show how to do it in this example.
> 
> But also here, there is likely an error somewhere in the lens data. A lens with 3.4 lambda peak-peak OPD at half field wouldn't be convincing.

The main issue is that the diameters of the lenses are not given in the patent so I have calculated these based on the known size of image size, and then measuring the diameters from the patent drawing. So really not an accurate way of doing it.

The Canon RF 50mm patent actually had the diameters specified.

BTW the performance is at F0.98 - would you expect that to be better than 3.4 lambda PTP at half field?

**Comment by jordens** [comment]
The diameters are not that relevant. The minimum diameter is purely determined by the aperture which is known. Off-axis they are just balancing vignetting vs off-axis aberration.
The problem with the Nikon lens definitions is certainly not the diameters.
OPD in the 0.1-0.3 range would be plausible. Otherwise the lens isn't even working properly on axis.
I would be inclined to mark all of these notebooks that don't achieve anywhere near the stated performance as erroneous.

**Comment by dibyendumajumdar** [comment]
I don't know if you can help diagnose the issue. I have checked and rechecked the patent information several times. I corrected a couple of mistakes I made earlier on.

Attached is the patent data:
[t.txt](https://github.com/quartiq/rayopt-notebooks/files/4499467/t.txt)

**Comment by jordens** [comment]
As mentioned in https://github.com/quartiq/rayopt-notebooks/pull/5#issuecomment-615386242:

* typos in patents (more common than you might think)
* OCR errors on scans and transcription errors between languages
* aspherics/conic: there are several different coefficient definitions
* air vs vacuum
* for color errors: dispersion data: is the material really fully defined by nd and vd?
* for off-axis errors: vignetting, aperture

You can exclude the last two by looking at the d line on axis. But the others may still be there.

**Comment by dibyendumajumdar** [comment]
The Nikkor appears to use Hikari glasses. If I were to add the Hikari glass catalog then presumably that would improve color info?

**Comment by dibyendumajumdar** [comment]
I tried with just d line but it didn't help - i.e. the PTP is still what it was. So presumably adding glass catalog will not help

**Pull request merged**
